version: "3"
services:
  credt_server:
    build: .
    command: "client.py"
    ports:
      - "3000:3000"
    networks:
      envoy_net:
        ipv4_address: 172.16.238.10

networks:
  envoy_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
